import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
    title: "Grids & Circles",
    description: "we make good coffee",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 3233ba9 (feat: 관리자 페이지 구현)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
<<<<<<< HEAD
            <Header/>
            <main className="container p-4 flex-grow mx-auto">{children}</main>
            <Footer/>
=======
          <Header />
          <main className="container p-4 flex-grow">{children}</main>
          <Footer />
>>>>>>> 3233ba9 (feat: 관리자 페이지 구현)
        </div>
      </body>
    </html>
  );
}
